"""add_teams_employees_shift_types_roster_settings

Revision ID: a309597e7b4a
Revises: 0001_initial_baseline
Create Date: 2026-06-25 14:50:17.581160
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a309597e7b4a'
down_revision: Union[str, None] = '0001_initial_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_settings_created_at'), 'settings', ['created_at'], unique=False)
    op.create_index('ix_settings_key', 'settings', ['key'], unique=False)
    op.create_table('shift_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_types_code'), 'shift_types', ['code'], unique=True)
    op.create_index(op.f('ix_shift_types_created_at'), 'shift_types', ['created_at'], unique=False)
    op.create_index('ix_shift_types_display_order', 'shift_types', ['display_order'], unique=False)
    op.create_index('ix_shift_types_is_active', 'shift_types', ['is_active'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_name')
    )
    op.create_index(op.f('ix_teams_created_at'), 'teams', ['created_at'], unique=False)
    op.create_index('ix_teams_display_order', 'teams', ['display_order'], unique=False)
    op.create_index('ix_teams_is_active', 'teams', ['is_active'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_code', sa.String(length=64), nullable=False),
    sa.Column('employee_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_employees_created_at'), 'employees', ['created_at'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_employee_name'), 'employees', ['employee_name'], unique=False)
    op.create_index('ix_employees_is_active', 'employees', ['is_active'], unique=False)
    op.create_index('ix_employees_team_active', 'employees', ['team_id', 'is_active'], unique=False)
    op.create_index('ix_employees_team_id', 'employees', ['team_id'], unique=False)
    op.create_table('roster',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_type_id', sa.Integer(), nullable=False),
    sa.Column('roster_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'roster_date', name='uq_roster_employee_date')
    )
    op.create_index(op.f('ix_roster_created_at'), 'roster', ['created_at'], unique=False)
    op.create_index('ix_roster_date_shift', 'roster', ['roster_date', 'shift_type_id'], unique=False)
    op.create_index('ix_roster_roster_date', 'roster', ['roster_date'], unique=False)
    op.create_index('ix_roster_shift_type_id', 'roster', ['shift_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roster_shift_type_id', table_name='roster')
    op.drop_index('ix_roster_roster_date', table_name='roster')
    op.drop_index('ix_roster_date_shift', table_name='roster')
    op.drop_index(op.f('ix_roster_created_at'), table_name='roster')
    op.drop_table('roster')
    op.drop_index('ix_employees_team_id', table_name='employees')
    op.drop_index('ix_employees_team_active', table_name='employees')
    op.drop_index('ix_employees_is_active', table_name='employees')
    op.drop_index(op.f('ix_employees_employee_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_created_at'), table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_teams_is_active', table_name='teams')
    op.drop_index('ix_teams_display_order', table_name='teams')
    op.drop_index(op.f('ix_teams_created_at'), table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_shift_types_is_active', table_name='shift_types')
    op.drop_index('ix_shift_types_display_order', table_name='shift_types')
    op.drop_index(op.f('ix_shift_types_created_at'), table_name='shift_types')
    op.drop_index(op.f('ix_shift_types_code'), table_name='shift_types')
    op.drop_table('shift_types')
    op.drop_index('ix_settings_key', table_name='settings')
    op.drop_index(op.f('ix_settings_created_at'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
